name: "Data: Create Jira ticket"
run-name: 'Sync Jira - Issue #${{ github.event.issue.number }} ("${{ github.event.issue.title }}")'

on:
  issues:
    types: [opened]
jobs:
  sync:
    name: Sync Items
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Sync
        uses: igorpecovnik/github-action-issue-to-jira@05d67c604cf13fc3c6c07d655d03439b0351747d # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          jiraHost: armbian.atlassian.net
          jiraUsername: ${{ secrets.JIRA_USER }}
          jiraPassword: ${{ secrets.JIRA_PASSWORD }}
          project: AR
          assignee: default_assignee
