name: "Data: Sync board list"
run-name: Update board JSON at armbian/armbian.github.io

on:
  push:
    paths:
      - "config/boards/*.*"
    branches: [main]

permissions:
  contents: read

jobs:
  update-board-list-dispatch:
    name: Send dispatch
    if: ${{ github.repository_owner == 'Armbian' }}
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: armbian/armbian.github.io
          event-type: "Data: Generate build engine inventory"
